language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
branches:
  except:
    - gh-pages
matrix:
  fast_finish: true
sudo: false
install:
  - python setup.py install
script:
  - python setup.py test
after_success:
  - coveralls
notifications:
  slack:
    - secure: dYxV7GVMdGmlaj2CRbXCpFFGA1a0lKVt1mrDSZxnZh6Rp3wMya3WC4SeTOClI5IiF9jJ/V9syNHbV//e/x16cMdEKaHapr+slpJs9IqU4ln2bNxh44GAyNFcfDftcMPbAduuDTiGUNoQY1K73GNtzRo86mvNmY2n2wlPwGCsJCQ= 
